import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { RainbowButton } from '@rainbow-me/rainbow-button';
import { useState, useEffect, useCallback } from 'react';
import Router from 'next/router';

export default function Landing() {
  const [connector, setConnector] = useState({});

  const onConnectorInitialized = useCallback(
    (connector) => {
      console.log(connector);
      setConnector(connector);
      Router.push('/dashboard');
    },
    [setConnector]
  );
  // Subscribe to connection events and update your app accordingly 
  const subscribeToEvents = useCallback(() => {
    connector.on('connect', (error, payload) => {
      if (error) {
        throw error;
      }
      // Get provided accounts and chainId
      const { accounts, chainId } = payload.params[0];
    });
    connector.on('session_update', (error, payload) => {
      if (error) {
        throw error;
      }
      // Get updated accounts and chainId
      const { accounts, chainId } = payload.params[0];
    });
    connector.on('disconnect', (error, payload) => {
      if (error) {
        throw error;
      }
      // Delete connector
      setConnector(null);
    });
  }, [connector]);

  useEffect(() => {
      subscribeToEvents
  }, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">MiniDao!</a>
        </h1>

        <p className={styles.description}>
          Get started by connecting your wallet{' '}
        </p>    
        <RainbowButton
          chainId={1}
          connectorOptions={{ bridge: 'https://bridge.walletconnect.org' }}
          onConnectorInitialized={() => onConnectorInitialized}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
