import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { RainbowButton } from '@rainbow-me/rainbow-button';

export default async function Landing() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">MiniDao!</a>
        </h1>

        <p className={styles.description}>
          Get started by connecting your wallet{' '}
        </p>    
        <RainbowButton
          chainId={1}
          connectorOptions={{ bridge: 'https://bridge.walletconnect.org' }}
          onConnectorInitialized={(connector) => console.log(connector)}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
